<?xml version="1.0"?>

<robot>
<!-- Everything is Discribed Here-->
<!-- http://classic.gazebosim.org/tutorials?tut=ros_usdf&cat=connect_ros -->
<!-- mu1 and mu2 are friction coefficients-->
<gazebo reference="body_link">
    <mu1>0.2</mu1>
    <mu2>0.2</mu2>
    <material>Gazebo/Red</material>
</gazebo>
<gazebo reference="right_wheel_link">
    <mu1>0.2</mu1>
    <mu2>0.2</mu2>
    <material>Gazebo/Yellow</material>
</gazebo>
<gazebo reference="left_wheel_link">
    <mu1>0.2</mu1>
    <mu2>0.2</mu2>
    <material>Gazebo/Yellow</material>
</gazebo>
<gazebo reference="caster_wheel_link">
    <mu1>0.000002</mu1>
    <mu2>0.000002</mu2>
    <material>Gazebo/Blue</material>
</gazebo>

<!-- Controller for the diffrential drive robot-->
<gazebo>
    <plugin name="diff_drive" filename="libgazebo_ros_diff_drive.so">
        <ros>
            <namespace></namespace>
        </ros>
        
        <!--Number of wheel pairs-->
        <num_wheel_pairs>1</num_wheel_pairs>

        <!-- wheels0-->
        <left_joint>left_wheel_joint</left_joint>
        <right_joint>right_wheel_joint</right_joint>

        <!-- Kinematics-->
        <wheel_separation>${body_link_y_dim+wheel_link_length}</wheel_separation>
        <wheel_diameter>${2*wheel_link_radius}</wheel_diameter>

        <!-- limits-->
        <max_wheel_torque>5000</max_wheel_torque>
        <max_wheel_acceleration>7.0</max_wheel_acceleration>

        <!-- Output -->
        <publish_odom>true</publish_odom>
        <publish_odom_tf>true</publish_odom_tf>
        <publish_wheel_tf>true</publish_wheel_tf>

        <odometry_frame>odom</odometry_frame>
        <robot_base_frame>dummy</robot_base_frame>
    </plugin>
</gazebo>
</robot>

